/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SawalJawabRouteImport } from './routes/sawal-jawab'
import { Route as QaRouteImport } from './routes/qa'
import { Route as MythRouteImport } from './routes/myth'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MythSlugRouteImport } from './routes/myth.$slug'
import { Route as LearnCategoryRouteImport } from './routes/learn.$category'
import { Route as AudioSlugRouteImport } from './routes/audio.$slug'
import { Route as AdminQaRouteImport } from './routes/admin.qa'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAudioRouteImport } from './routes/admin.audio'
import { Route as LearnCategorySlugRouteImport } from './routes/learn.$category.$slug'
import { Route as AdminContentMythsRouteImport } from './routes/admin.content.myths'
import { Route as AdminContentArticlesRouteImport } from './routes/admin.content.articles'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SawalJawabRoute = SawalJawabRouteImport.update({
  id: '/sawal-jawab',
  path: '/sawal-jawab',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const MythRoute = MythRouteImport.update({
  id: '/myth',
  path: '/myth',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MythSlugRoute = MythSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MythRoute,
} as any)
const LearnCategoryRoute = LearnCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => LearnRoute,
} as any)
const AudioSlugRoute = AudioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AudioRoute,
} as any)
const AdminQaRoute = AdminQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAudioRoute = AdminAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => AdminRoute,
} as any)
const LearnCategorySlugRoute = LearnCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnCategoryRoute,
} as any)
const AdminContentMythsRoute = AdminContentMythsRouteImport.update({
  id: '/content/myths',
  path: '/content/myths',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentArticlesRoute = AdminContentArticlesRouteImport.update({
  id: '/content/articles',
  path: '/content/articles',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/audio': typeof AudioRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/myth': typeof MythRouteWithChildren
  '/qa': typeof QaRoute
  '/sawal-jawab': typeof SawalJawabRoute
  '/search': typeof SearchRoute
  '/admin/audio': typeof AdminAudioRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/qa': typeof AdminQaRoute
  '/audio/$slug': typeof AudioSlugRoute
  '/learn/$category': typeof LearnCategoryRouteWithChildren
  '/myth/$slug': typeof MythSlugRoute
  '/admin/content/articles': typeof AdminContentArticlesRoute
  '/admin/content/myths': typeof AdminContentMythsRoute
  '/learn/$category/$slug': typeof LearnCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/audio': typeof AudioRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/myth': typeof MythRouteWithChildren
  '/qa': typeof QaRoute
  '/sawal-jawab': typeof SawalJawabRoute
  '/search': typeof SearchRoute
  '/admin/audio': typeof AdminAudioRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/qa': typeof AdminQaRoute
  '/audio/$slug': typeof AudioSlugRoute
  '/learn/$category': typeof LearnCategoryRouteWithChildren
  '/myth/$slug': typeof MythSlugRoute
  '/admin/content/articles': typeof AdminContentArticlesRoute
  '/admin/content/myths': typeof AdminContentMythsRoute
  '/learn/$category/$slug': typeof LearnCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/audio': typeof AudioRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/myth': typeof MythRouteWithChildren
  '/qa': typeof QaRoute
  '/sawal-jawab': typeof SawalJawabRoute
  '/search': typeof SearchRoute
  '/admin/audio': typeof AdminAudioRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/qa': typeof AdminQaRoute
  '/audio/$slug': typeof AudioSlugRoute
  '/learn/$category': typeof LearnCategoryRouteWithChildren
  '/myth/$slug': typeof MythSlugRoute
  '/admin/content/articles': typeof AdminContentArticlesRoute
  '/admin/content/myths': typeof AdminContentMythsRoute
  '/learn/$category/$slug': typeof LearnCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/audio'
    | '/learn'
    | '/myth'
    | '/qa'
    | '/sawal-jawab'
    | '/search'
    | '/admin/audio'
    | '/admin/dashboard'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/qa'
    | '/audio/$slug'
    | '/learn/$category'
    | '/myth/$slug'
    | '/admin/content/articles'
    | '/admin/content/myths'
    | '/learn/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/audio'
    | '/learn'
    | '/myth'
    | '/qa'
    | '/sawal-jawab'
    | '/search'
    | '/admin/audio'
    | '/admin/dashboard'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/qa'
    | '/audio/$slug'
    | '/learn/$category'
    | '/myth/$slug'
    | '/admin/content/articles'
    | '/admin/content/myths'
    | '/learn/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/audio'
    | '/learn'
    | '/myth'
    | '/qa'
    | '/sawal-jawab'
    | '/search'
    | '/admin/audio'
    | '/admin/dashboard'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/qa'
    | '/audio/$slug'
    | '/learn/$category'
    | '/myth/$slug'
    | '/admin/content/articles'
    | '/admin/content/myths'
    | '/learn/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AudioRoute: typeof AudioRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
  MythRoute: typeof MythRouteWithChildren
  QaRoute: typeof QaRoute
  SawalJawabRoute: typeof SawalJawabRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sawal-jawab': {
      id: '/sawal-jawab'
      path: '/sawal-jawab'
      fullPath: '/sawal-jawab'
      preLoaderRoute: typeof SawalJawabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myth': {
      id: '/myth'
      path: '/myth'
      fullPath: '/myth'
      preLoaderRoute: typeof MythRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myth/$slug': {
      id: '/myth/$slug'
      path: '/$slug'
      fullPath: '/myth/$slug'
      preLoaderRoute: typeof MythSlugRouteImport
      parentRoute: typeof MythRoute
    }
    '/learn/$category': {
      id: '/learn/$category'
      path: '/$category'
      fullPath: '/learn/$category'
      preLoaderRoute: typeof LearnCategoryRouteImport
      parentRoute: typeof LearnRoute
    }
    '/audio/$slug': {
      id: '/audio/$slug'
      path: '/$slug'
      fullPath: '/audio/$slug'
      preLoaderRoute: typeof AudioSlugRouteImport
      parentRoute: typeof AudioRoute
    }
    '/admin/qa': {
      id: '/admin/qa'
      path: '/qa'
      fullPath: '/admin/qa'
      preLoaderRoute: typeof AdminQaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audio': {
      id: '/admin/audio'
      path: '/audio'
      fullPath: '/admin/audio'
      preLoaderRoute: typeof AdminAudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/learn/$category/$slug': {
      id: '/learn/$category/$slug'
      path: '/$slug'
      fullPath: '/learn/$category/$slug'
      preLoaderRoute: typeof LearnCategorySlugRouteImport
      parentRoute: typeof LearnCategoryRoute
    }
    '/admin/content/myths': {
      id: '/admin/content/myths'
      path: '/content/myths'
      fullPath: '/admin/content/myths'
      preLoaderRoute: typeof AdminContentMythsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/articles': {
      id: '/admin/content/articles'
      path: '/content/articles'
      fullPath: '/admin/content/articles'
      preLoaderRoute: typeof AdminContentArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAudioRoute: typeof AdminAudioRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminQaRoute: typeof AdminQaRoute
  AdminContentArticlesRoute: typeof AdminContentArticlesRoute
  AdminContentMythsRoute: typeof AdminContentMythsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAudioRoute: AdminAudioRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminQaRoute: AdminQaRoute,
  AdminContentArticlesRoute: AdminContentArticlesRoute,
  AdminContentMythsRoute: AdminContentMythsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AudioRouteChildren {
  AudioSlugRoute: typeof AudioSlugRoute
}

const AudioRouteChildren: AudioRouteChildren = {
  AudioSlugRoute: AudioSlugRoute,
}

const AudioRouteWithChildren = AudioRoute._addFileChildren(AudioRouteChildren)

interface LearnCategoryRouteChildren {
  LearnCategorySlugRoute: typeof LearnCategorySlugRoute
}

const LearnCategoryRouteChildren: LearnCategoryRouteChildren = {
  LearnCategorySlugRoute: LearnCategorySlugRoute,
}

const LearnCategoryRouteWithChildren = LearnCategoryRoute._addFileChildren(
  LearnCategoryRouteChildren,
)

interface LearnRouteChildren {
  LearnCategoryRoute: typeof LearnCategoryRouteWithChildren
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnCategoryRoute: LearnCategoryRouteWithChildren,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface MythRouteChildren {
  MythSlugRoute: typeof MythSlugRoute
}

const MythRouteChildren: MythRouteChildren = {
  MythSlugRoute: MythSlugRoute,
}

const MythRouteWithChildren = MythRoute._addFileChildren(MythRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AudioRoute: AudioRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
  MythRoute: MythRouteWithChildren,
  QaRoute: QaRoute,
  SawalJawabRoute: SawalJawabRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
